## Example 5 - Fault Information System, column reasoning

In [20]:
import pandas as pd
from isolability import pairwise_relationships as pr
from isolability import matrices_and_indices as ind

#### Fault Information System

In [21]:
fis_df = pd.read_csv('example5/fis.csv', sep=';', index_col=0, dtype=str)
fis_df

       f_1  f_2    f_3    f_4
s_1   -1,1    1      0   -1,1
s_2      1    1      0      1
s_3      0    0   -1,1      1

In [22]:
fis_df = fis_df.map(lambda x: set(a.strip() for a in x.split(',')))
fis_df

         f_1  f_2      f_3      f_4
s_1  {1, -1}  {1}      {0}  {1, -1}
s_2      {1}  {1}      {0}      {1}
s_3      {0}  {0}  {1, -1}      {1}

#### Exploration of pairwise isolabity relationships
* Function arguments are fault **indices** starting from 0, so pr.RS_C_FIS(fis_df, 1, 2) checks faults $f_2$ and $f_3$
* Avaliable relations:
    - RN_C_FIS - non-isolable
    - RUN_C_FIS - unilaterally non-isolable
    - RUC_C_FIS - unilaterally conditionally isolable
    - RC_C_FIS - bilaterally conditionally isolable
    - RW_C_FIS - weakly isolable
    - RS_C_FIS - strongly isolable

In [31]:
pr.RUN_C_FIS(fis_df, 1, 0)

True

#### EIM matrix

In [29]:
eim = ind.EIM_C_FIS(fis_df)
eim

array([[0. , 0.4, 2. , 1. ],
       [0. , 0. , 2. , 1. ],
       [2. , 2. , 0. , 2. ],
       [1. , 1. , 2. , 0. ]])

#### $C\Delta$ coefficient

In [32]:
c_delta = ind.C_Delta(eim)
print(f"{c_delta:.3f}")

1.367

#### $C^*\Delta$ coefficient

In [33]:
c_star_delta = ind.C_star_Delta(eim)
print(f"{c_star_delta:.3f}")

0.867

#### Robustness coefficient $\gamma$

In [35]:
print(f"{c_delta - c_star_delta:.3f}")

0.500